### ISSUE TITLE
Eslint without Babel?

### ISSUE THREAD

**Issue by Leeds-eBooks** [flowtype/flow-remove-types#25]
In the readme you mention eslint support and link to `eslint-plugin-flowtype`, where it says that you need the `babel-eslint` parser to handle flow types (which negates the use of `flow-remove-types` entirely). I'm a little confused – can I use `flow-remove-types` with `eslint`?

**Comment by leebyron** [comment]
babel-eslint doesn't negate the use of flow-remove-types! All it does is change the parser that eslint uses to look at files. Consider the name "babel-eslint" a misnomer due to the history of the babel project. A more accurate name (though harder to remember) might be "eslint-babylon-parser" because it just directs eslint to use babylon as its parser. 

This package is *also* based on babylon. If we were to publish a `eslint-flow-remove-types` parser, it would be almost identical to `babel-eslint`.

**Comment by Leeds-eBooks** [comment]
@leebyron Thanks for your reply. Reading back, my message came across quite combative, sorry about that. I think I was a little confused by the readme link. `flow-remove-types` is not currently used by `eslint`, and cannot be, is that correct? In other words, there is no parser or plugin for `eslint` that uses `flow-remove-types`.

If that's the case, then the part in this readme that refers to `eslint` really means "use of _flow_ with eslint" rather than "use of _flow-remove-types_ with eslint". Perhaps that is confusing to people other than me... perhaps it isn't!
